# Services for RTKkey integration
refresh_data:
  name: Refresh data
  description: Force refresh all RTKkey data
  fields:
    entity_id:
      name: Entity
      description: Specific entity to refresh (optional)
      selector:
        entity:
          domain: sensor
          integration: rtkkey